version: '3.8'

services:
  feed-revival-web:
    container_name: feed-revival
    build: .
    ports:
      - "5000:8255"
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: